ultimate_cron.settings:
  type: config_object
  label: Ultimate cron settings
  mapping:
    bypass_transactional_safe_connection:
      type: boolean
      label: 'Bypass transactional connection'
    queue:
      type: mapping
      label: Queue settings
      mapping:
        enabled:
          type: boolean
          label: Toggle queing jobs
        timeouts:
          type: mapping
          label: Timeouts
          mapping:
            lease_time:
              type: integer
              label: Time to claim item
            time:
              type: integer
              label: Time to process item
        delays:
          type: mapping
          label: Delays
          mapping:
            empty_delay:
              type: integer
              lebel: Time to idle when queue is empty
            item_delay:
              type: integer
              label: Time to idle when finished with item
        throttle:
          type: mapping
          label: Timeouts
          mapping:
            enabled:
              type: boolean
              label: Toggles throttling of queues
            threads:
              type: integer
              label: Number of threads for queues
            threshold:
              type: integer
              label: Number of items needed for a queue
    default_plugins:
      type: mapping
      label: Default Plugins
      mapping:
        launcher:
          type: string
          label: Launcher
        scheduler:
          type: string
          label: Scheduler
        Logger:
          type: string
          label: Logger
    launcher:
      type: sequence
      label: Launcher Settings
      sequence:
        type: ultimate_cron.plugin.launcher.[id]
        label: Launcher
    logger:
      type: sequence
      label: Logger Settings
      sequence:
        type: ultimate_cron.plugin.logger.[id]
        label: Launcher
    scheduler:
      type: sequence
      label: Schedulers Settings
      sequence:
        type: ultimate_cron.plugin.scheduler.[id]
        label: Scheduler

# @todo make schema pluggable
ultimate_cron.job.*:
  type: config_entity
  label: 'Cron Job'
  mapping:
    title:
      type: label
      label: 'Title'
    id:
      type: string
      label: 'Machine-readable name'
    module:
      type: string
      label: 'Module Name'
    callback:
      type: string
      label: 'Callback'
    scheduler:
      type: ultimate_cron.plugin.scheduler.[id]
      label: 'Scheduler'
    launcher:
      type: ultimate_cron.plugin.launcher.[id]
      label: 'Launcher'
    logger:
      type: ultimate_cron.plugin.logger.[id]
      label: 'Logger'

ultimate_cron.plugin.scheduler:
  type: mapping
  label: 'Scheduler configuration'
  mapping:
    id:
      type: string
      label: 'ID'
    uuid:
      type: string
      label: 'UUID'
    rules:
      type: sequence
      label: 'Scheduler rules'
      sequence:
        type: string
        label: 'Scheduling rule'

ultimate_cron.plugin.scheduler.simple:
  type: ultimate_cron.plugin.scheduler
  label: 'Scheduler configuration'
  mapping:
    id:
      type: string
      label: 'ID'
    uuid:
      type: string
      label: 'UUID'
    rules:
      type: sequence
      label: 'Scheduler rules'
      sequence:
        type: string
        label: 'Scheduling rule'

ultimate_cron.plugin.scheduler.crontab:
  type: ultimate_cron.plugin.scheduler
  label: 'Scheduler configuration'
  mapping:
    catch_up:
      type: integer
      label: 'Timeout (s) after job run'

ultimate_cron.plugin.launcher:
  type: mapping
  label: 'Scheduler configuration'
  mapping:
    id:
      type: string
      label: 'ID'
    uuid:
      type: string
      label: 'UUID'
ultimate_cron.plugin.launcher.serial:
  type: ultimate_cron.plugin.launcher
  label: 'Scheduler configuration'
  mapping:
    timeouts:
      type: mapping
      label: 'Timeout settings'
      mapping:
        lock_timeout:
          type: integer
          label: 'Lock timeout'
        max_execution_time:
          type: integer
          label: 'Max execution time'
    launcher:
      type: mapping
      label: 'Launcher settings'
      mapping:
        max_threads:
          type: integer
          label: 'Max threads'
        poorman_keepalive:
          type: boolean
          label: 'Keepalive'
        thread:
          type: integer
          label: 'Thread'

ultimate_cron.plugin.logger:
  type: mapping
  label: 'Scheduler configuration'
  mapping:
    id:
      type: string
      label: 'ID'
    uuid:
      type: string
      label: 'UUID'
ultimate_cron.plugin.logger.database:
  type: ultimate_cron.plugin.logger
  label: 'Scheduler configuration'
  mapping:
    method:
      type: string
      label: 'Method'
    expire:
      type: integer
      label: 'Expiration'
    retain:
      type: integer
      label: 'Retain X amount of logs'

ultimate_cron.plugin.logger.cache:
  type: ultimate_cron.plugin.logger
  label: 'Scheduler configuration'
  mapping:
    bin:
      type: string
      label: 'Cache bin to use for storing logs'
    timeout:
      type: integer
      label: 'Timeout (s) before cache entry expires'
